config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  get 'design', to: 'pages#design'


  resources :yachts do
    resources :bookings, except: [ :show, :index ]
    resources :reviews, only: [ :new, :create, :index, :destroy]
  end

  get 'yachts/dashboard/users/:id', to: 'users#dashboard', as: :dashboard

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :yacht

  validates :booking_start, presence: true
  validates :booking_end, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :yacht

  validates :rating, presence: true, inclusion: { in: [1,2,3,4,5] }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :yachts
  has_many :bookings
  has_many :rented_yachts, through: :bookings, source: :yacht

  mount_uploader :photo, PhotoUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/yacht.rb
class Yacht < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :previous_users, through: :bookings, source: :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_yacht
  before_action :set_booking, only: [ :edit, :update, :destroy ]

  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.yacht = @yacht
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to dashboard_path(current_user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @booking.update(booking_params)
    if @booking.save
      redirect_to dashboard_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy
    redirect_to dashboard_path(current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:booking_start, :booking_end)
  end

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def set_yacht
    @yacht = Yacht.find(params[:yacht_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :design ]
  def home
  end

  def design

  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index ]
  before_action :set_yacht

  def index
    @reviews = @yacht.reviews
  end

  def new
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @review.yacht = @yacht
    authorize @review
    if @review.save
      redirect_to yacht_path(@yacht)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    authorize @review
    @review.destroy
    redirect_to yacht_path(@yacht)
  end

  private

  def set_yacht
    @yacht = Yacht.find(params[:yacht_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :dashboard ]

  def dashboard
    @hosted = @user.yachts
    @bookings = @user.bookings
  end

  private

  def set_user
    @user = User.find(params[:id])
    authorize @user
  end
end

app/controllers/yachts_controller.rb
class YachtsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  before_action :set_yacht, only: [ :show, :edit, :update, :destroy ]

  def index
    if params[:query].present?
      sql_query = "name ILIKE :query OR address ILIKE :query"
      @yachts = policy_scope(Yacht).where(sql_query, query: "%#{params[:query]}%")
      respond_to do |format|
        format.html { redirect_to yachts_path }
        format.js # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      @yachts = policy_scope(Yacht)
    end
  end

  def show
    @booking = Booking.new
    @yacht = set_yacht
    @marker = [{lng: @yacht.longitude,
    lat: @yacht.latitude,infoWindow: render_to_string(partial: "infowindow", locals: { yacht: @yacht }), image_url: helpers.asset_url('ancnhor.png')}]
  end

  def new
    @yacht = Yacht.new
    authorize @yacht
  end

  def create
    @yacht = Yacht.new(yacht_params)
    @yacht.user = current_user
    authorize @yacht
    if @yacht.save
      redirect_to dashboard_path(current_user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @yacht.update(yacht_params)
    authorize @yacht
    if @yacht.save
      redirect_to yachts_path
    else
      render :edit
    end
  end

  def destroy
    @yacht.destroy
    redirect_to dashboard_path(current_user)
  end

  private

  def set_yacht
    @yacht = Yacht.find(params[:id])
    authorize @yacht
  end

  def yacht_params
    params.require(:yacht).permit(:name, :description, :price_per_day, :photo, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_new.html.erb
<div class="background-form-booking">
  <div id="container-form" class="formbooking" >
  <%= simple_form_for([@yacht, @booking]) do |f| %>
    <div div class="form-inputs-booking"><%= f.error_notification %>
      <%= f.input :booking_start, as: :string, required: false, input_html: { id: "range_start" } %>
      <%= f.input :booking_end, as: :string, required: false, input_html: { id: "range_end" } %>
      <%= f.button :submit, class: "btn-yours button-center" %></div>
  <% end %>
  </div>
</div>

app/views/bookings/edit.html.erb
<%= simple_form_for([@yacht, @booking]) do |f| %>
  <%= f.error_notification %>
  <%= f.input :booking_date %>
<%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <link rel="shortcut icon" type="image/x-icon" href="/assets/logo.png">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->

  </head>
  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/design.html.erb
<!--banner-->


<h1>Header one </h1>



<a href="#" class="yacht-link">ALL </a>

<a href="#" class="btn-yours">MY BUTTON</a>



<div class="container-fluid">
  <div class="col-lg-6 col-lg-offset-0 col-md-6 col-md-offset-0 col-sm-10 col-sm-offset-1 col-xs-12">
    <figure>
      <div class="media" style="background-image:url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/584938/bg_15.png);"></div>
      <figcaption>
        <svg viewBox="0 0 200 200" version="1.1" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg">
          <defs>
            <mask id="mask" x="0" y="0" width="100%" height="100%">
              <rect id="alpha" x="0" y="0" width="100%" height="100%"></rect>
              <text class="title" dx="50%" dy="2.5em">ENJOY</text>
            </mask>
          </defs>
          <rect id="base" x="0" y="0" width="100%" height="100%"></rect>
        </svg>
        <div class="body">
          <p>Enamel pin selvage health goth edison bulb, venmo glossier tattooed hella butcher cred iPhone.</p>
        </div>
      </figcaption><a href="#"></a>
    </figure>
  </div>

<!--link-->
<a href="#" class="yacht-link">ALL </a>

<!--button-->
<a href="#" class="btn-yours">MY BUTTON</a>



<!--card-->

<div class="container">
  <div class="wrapper">
    <div class="row">
      <%  %>
       <div class="col-xs-12  col-md-4 col-sm-6 ">
          <div class="info">

        <div class="card"><%= image_tag"https://images.unsplash.com/photo-1525092703556-f2d561118425?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1400&q=60", alt: "Le Wagon", width: 200 %>
              <h2> Yacht name</h2>
        <div class="square">


         <div class="card-body">
              <h3>From$103 / night</h3>
              <a href="#" class="btn-card">Details</a>
         </div>
       </div>
          </div>
        </div>
      </div>
    <% %>
    </div>
  </div>
</div>








<!-- <div class="container">
  <div class="wrapper">
    <div class="row">
       <% #@yachts.each do |yacht| %>
       <div class="col-xs-12  ">
       <div class="big-card">
          <div class="card"><%=#cl_image_tag  yacht.photo, height: 500, width: 600, crop: :fill %>
             </div>
           <div class="info">
             <div class="square">
          <div class="card-body">
               <h2>  <%=# yacht.name %></h2>
               <h3><%= #yacht.price_per_day %> $ per night</h3>
            <a href="<%= #yacht_path(yacht) %>" class="btn-card">Details</a>
          </div>
          </div>
           </div>

       </div>
      </div>
    <%3end %>
    </div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.5) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1523496922380-91d5afba98a3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2689&q=80);">
    <div class="logo">
      <div>
        <h3>N˚1</h3>
        <h1>Yacht Square</h1>
      </div>
    </div>
    <div class="button-discover">
      <div>
        <%= link_to "Discover", yachts_path, class:"text" %>
      </div>
    </div>
  </div>

app/views/reviews/_index.html.erb
<h1><%= @yacht.name %>'s reviews</h1>
<% if @yacht.reviews.present? %>
  <% @yacht.reviews.each do |review| %>
    <div class="yacht-review-container">
      <p></p>
      <p><%= review.content %></p>
     <%= "*" * review.rating %>
      <%= link_to yacht_review_path(@yacht, review), method:"delete", class: "review-delete-btn" do %>
        <i class="fas fa-trash"></i>
      <% end %>
    </div>
  <% end %>
<% else %>
  <h3>no reviews yet</h3>
<% end %>

app/views/reviews/new.html.erb
<div class="background-form">
  <div id="container-host" class="formform">
    <h2 class="text-center logging-in form">Share your experience</h2>
    <div class="row">
      <div class="col-xs-4 col-xs-offset-3">
        <%= simple_form_for([@yacht, @review]) do |f| %>
          <div class="form-inputs">
            <%= f.input :content %>
            <%= f.input :rating %>
            <div class="form-actions">
              <%= f.button :submit, "Share", :class => "btn-yours button-center" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
 <%= link_to "Explore", yachts_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Host", new_yacht_path , class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Dashboard", dashboard_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to "Become a host", new_yacht_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/dashboard.html.erb
<div id="parallax-world-of-ugg">


<section>
  <div class="title">
       <h3>Hi </h3>
    <h1><%= current_user.email%></h1>
  </div>
</section>


<section>




      <div class="parallax-one" style="background-image: url('https://images.unsplash.com/photo-1419032185395-8131e3576bbb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60');">
       <h2>Your Posts</h2>
      </div>

</section> <!--section one-->

<section>
  <div class="block">
      <div class="row row-dashboard">
        <% @hosted.each do |post| %>
          <div class="col-xs-12 col-md-6 ">
            <div class="big-card-dashboard">
              <% background_url = post.photo.present? ? cl_image_path(post.photo, height: 500, crop: :fit) :  image_path("yachtdefault.jpg") %>
              <div class="card-dashboard" style="background-image: url('<%= background_url %>')">
                <div class="">
                  <div class="square-dashboard">
                    <div class="card-body-dashboard">
                      <p> <%= post.name %></p>
                      <div class="info-dashboard">
                        <p><%= post.price_per_day %> $ per night</p>
                        <%= link_to "delete", yacht_path(post), method:"delete"  %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
          </div>
        </div> <!-- closing col -->
        <%end %>
      </div> <!-- closing row -->
  </div> <!-- closing block -->

</section>


<section>

      <div class="parallax-one" style="background-image: url('https://images.unsplash.com/photo-1435527173128-983b87201f4d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1400&q=60');">
       <h2>Your Bookings<h2>
      </div>

<section>
  <div class="title">
       <h3>Ready </h3>
    <h1>for your next vacation</h1>
  </div>
</section>
</section> <!--section one-->
<div class="block">
<h1>You have <%= @bookings.count %> bookings</h1>

    <!-- <div class="wrapper"> -->


<h2>Checkout:</h2>
<% @bookings.each do |booking| %>
<p>Cruise duration: <%= (booking.booking_start - booking.booking_end).abs.to_i %> days</p>
<p>Starting <%= booking.booking_start.strftime("%b %-d, %Y") %> until <%= booking.booking_end.strftime("%b %-d, %Y") %></p>
<p>Total price: <%= booking.yacht.price_per_day * (booking.booking_start - booking.booking_end).abs.to_i %>$</p>
<div class="btn btn-warning">Checkout</div>
<% end %>
</div>

app/views/users/dashboard_booked.html.erb
<div class="cards-wrapper">
  <h1 class="vertical-text yacht-header-design yacht-header-longline yacht-header-shortline">TRIPS</h1>
  <div class="container">
    <!-- <div class="wrapper"> -->
      <div class="row">
         <% @bookings.each do |trip| %>
         <div class="col-xs-12  col-md-6 ">
          <div class="big-card">
          <% if trip.yacht.photo.present? %>
          <div class="card" style="background-image: url('<%= cl_image_path trip.yacht.photo, height: 500, crop: :fit %>')">
            <div class="">
              <div class="square">
           <div class="card-body">
                <h2>  <%= trip.yacht.name %></h2>
                <h6>Starting <%= trip.booking_start.strftime("%b %-d, %Y") %> until <%= trip.booking_end.strftime("%b %-d, %Y") %></h6>

                <div class="info">
                  <h3><%= trip.yacht.price_per_day %> $ per night</h3>
                  <h4><%= trip.yacht.description %></h4>
                  <%= link_to "Edit booking", edit_yacht_booking_path(trip.yacht, trip) %>
                  <%= link_to "Delete booking", yacht_booking_path(trip.yacht, trip), method:"delete" %>
                </div>

           </div>
           </div>
            </div>
          </div>
          <% else %>
           <div class="card" style="background-image: url('<%= image_path "yachtdefault.jpg", height: 500, crop: :fit %>')">
            <div class="">
              <div class="square">
           <div class="card-body">
                <h2>  <%= trip.yacht.name %></h2>
                <%= trip.booking_start.strftime("%b %-d, %Y") %>
                <%= trip.booking_end.strftime("%b %-d, %Y") %>
                <div class="info">
                  <h3><%= trip.yacht.price_per_day %> $ per night</h3>
                  <h4><%= trip.yacht.description %></h4>
                  <%= link_to "Edit booking", edit_yacht_booking_path(trip.yacht, trip) %>
                  <%= link_to "Delete booking", yacht_booking_path(trip.yacht, trip), method:"delete" %>
                </div>

           </div>
           </div>
            </div>
          </div>
          <% end %>
          </div>
        </div>
      <%end %>

      </div>
  <!--   </div> -->
  </div>
<h1>You have <%= @bookings.count %> bookings</h1>
<% @bookings.each do |booking| %>
<h3>Cruise duration: <%= (booking.booking_start - booking.booking_end).abs.to_i %> days</h3>
<h6>Starting <%= booking.booking_start.strftime("%b %-d, %Y") %> until <%= booking.booking_end.strftime("%b %-d, %Y") %></h6>
<h3>Total price: <%= booking.yacht.price_per_day * (booking.booking_start - booking.booking_end).abs.to_i %>$</h3>
<div class="btn btn-warning">Checkout</div>
<% end %>

app/views/users/template.html.erb
      <div class="row--dashboard">
         <% @bookings.each do |trip| %>
         <div class="col-xs-12  col-md-6 ">
          <div class="big-card-dashboard">
            <% if trip.yacht.photo.present? %>
              <div class="card-dashboard" style="background-image: url('<%= cl_image_path trip.yacht.photo, height: 500, crop: :fit %>')">
                <div class="">
                  <div class="square-dashboard">
                    <div class="card-body-dashboard">
                      <h1>  <%= trip.yacht.name %></h1>
                      <h6>Starting <%= trip.booking_start.strftime("%b %-d, %Y") %> until <%= trip.booking_end.strftime("%b %-d, %Y") %></h6>
                      <div class="info--dashboard">
                        <h3><%= trip.yacht.price_per_day %> $ per night</h3>
                        <%= link_to "Delete booking", yacht_booking_path(trip.yacht, trip), method:"delete" %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
          <% else %>
           <div class="card-dashboard" style="background-image: url('<%= image_path "yachtdefault.jpg", height: 500, crop: :fit %>')">
            <div class="">
              <div class="square-dashboard">
           <div class="card-body">
                <h3>  <%= trip.yacht.name %></h3>
                <%= trip.booking_start.strftime("%b %-d, %Y") %>
                <%= trip.booking_end.strftime("%b %-d, %Y") %>
                <div class="info">
                  <p><%= trip.yacht.price_per_day %> $ per night</p>

                  <%= link_to "Delete booking", yacht_booking_path(trip.yacht, trip), method:"delete" %>
                </div>
           </div>
           </div>
            </div>
          </div>
          <% end %>
          </div>
      <%end %>
      </div>

app/views/yachts/_infowindow.html.erb
<h1>hey</h1>

app/views/yachts/_list.html.erb
<% @yachts.each do |yacht| %>
           <div class="col-xs-12  col-md-6 ">
             <div class="big-card">
               <% if yacht.photo.present? %>
                 <div class="card" style="background-image: url('<%= cl_image_path yacht.photo, height: 500, crop: :fit %>')">
                     <div class="">
                       <div class="square">
                         <div class="card-body">
                           <h2>  <%= yacht.name %></h2>
                             <div class="info">
                               <h3><%= yacht.price_per_day %> $ per night</h3>
                               <a href="<%= yacht_path(yacht) %>" class="btn-card">Details</a>
                             </div>
                           </div>
                         </div>
                        </div>
                       </div>
               <% else %>
                 <div class="card" style="background-image: url('<%= image_path "yachtdefault.jpg", height: 500, crop: :fit %>')">
                   <div class="">
                     <div class="square">
                       <div class="card-body">
                         <h2>  <%= yacht.name %></h2>
                           <div class="info">
                             <h3><%= yacht.price_per_day %> $ per night</h3>
                              <a href="<%= yacht_path(yacht) %>" class="btn-card">Details</a>
                           </div>
                         </div>
                       </div>
                     </div>
                   </div>
                 <% end %>
               </div>
             </div>
         <%end %>

app/views/yachts/dashboard.html.erb
<h1>These are your hosted yachts:</h1>

<h1>These are your booked yachts:</h1>

app/views/yachts/edit.html.erb
<%= simple_form_for(@yacht) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price_per_day %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
<%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/yachts/index.js.erb
function emptyForm() {
  const input = document.getElementById('search-input');
  input.value = "";
}

function showYachts(resultsHTML) {
  const yachts = document.getElementById('yacht-cards');
  yachts.innerHTML = resultsHTML;
}


emptyForm()
showYachts('<%= j render "list", yachts: @yachts %>')

app/views/yachts/new.html.erb
<div class="background-form">
  <div id="container-host" class="formform">
    <h2 class="text-center logging-in form">Host your yacht</h2>
    <div class="row">
      <div class="col-xs-4 col-xs-offset-3">
        <%= simple_form_for(@yacht) do |f| %>
          <div class="form-inputs">
            <%= f.input :name %>
            <%= f.input :description %>
            <%= f.input :price_per_day %>
            <%= f.input :address %>
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
            <div class="form-actions">
              <%= f.button :submit, "Confirm your post", :class => "btn-yours button-center" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/yachts/show.html.erb
<div id="parallax-world-of-ugg">

<section>
  <div class="title">
       <h3>Welcome aboard on the</h3>
    <h1> <%= @yacht.name %></h1>
  </div>
</section>

<section>
    <% if @yacht.photo.present? %>
      <div class="parallax-one" style="background-image: url('<%= cl_image_path @yacht.photo %>');">
        <h2><%= @yacht.name %></h2>
      </div>
    <% else %>
      <div class="parallax-one" style="background-image: url('<%= image_path "yachtdefault.jpg", alt: "alttext" %>');">
       <h2><%= @yacht.name %></h2>
      </div>
    <% end %>
</section>

<section>
  <div class="block">

    <p><span class="first-character sc">I</span><%= @yacht.description %></p>
    <p class="line-break margin-top-10"></p>
    <p class="margin-top-10">
  <p><%= @yacht.price_per_day %>$ per night</p>

 <p>Contact: <%= @yacht.user.email %></p>
 </p>
<p><%= link_to "Back", yachts_path, class: 'yacht-link' %></p>

<div class="review-border">
  <%= render "reviews/index" %>
<% if @yacht.reviews.present? %>
  <a href="<%= new_yacht_review_path(@yacht) %>" class="btn-card shift-up-added-review"  >Share your experience with us</a>
<% else %>
  <a href="<%= new_yacht_review_path(@yacht) %>" class="btn-card shift-up"  >Share your experience with us</a>
<% end %>
</div>
    </div>


</section>


<section class="flex-show">


  <%= render 'bookings/new' %>

<div
  id="map" class="parallax-two"
  style="
  height: 50vh;"
  data-markers="<%= @marker.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

</section>
     <% if @yacht.photo.present? %>
        <div class="parallax-three" style="background-image: url('<%= cl_image_path @yacht.photo %>');">
        <h2><%= @yacht.name %></h2>
      <% else %>
          <div class="parallax-three" style="background-image: url('<%= image_path "yachtdefault.jpg", alt: "alttext" %>');">
        <h2><%= @yacht.name %></h2>
    </div>
    <% end %>
</section>